[tool.poetry]
name = "test-cicd"
version = "0.1.0"
description = ""
authors = ["dima cheban <dimacheban23@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
